export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CHANGE_CITY_ON_DISPLAY = 'CHANGE_CITY_ON_DISPLAY';
export const FETCH_APPARTMENTUNITS = 'FETCH_APPARTMENTUNITS';
export const CHANGE_CURRENT_NAV = 'CHANGE_CURRENT_NAV';